name: variant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - biopython
  - numpy
  - pandas
  - pyyaml
  - plotly
  - networkx
  - python-igraph
  - viennarna  # RNA secondary structure prediction for PRF analysis
  - pip
  - pip:
    - fuzzysearch==0.7.3 
    - more-itertools>=8.12.0
    - kaleido>=1.0.0